- name: Vite Github Pages Deployer

  # You may pin to the exact commit or the version.

  # uses: skywarth/vite-github-pages-deployer@c90e1fa4391d6740ba83549839c9b8109fecb531

  uses: skywarth/vite-github-pages-deployer@v1.1.0

  with:

    # Public base path string for vite, this affects the routing, history and asset links. Make sure to provide appropriately since Github Pages stores your app in a directory under a subdomain.

    public_base_path: # optional, default is /${{ github.event.repository.name }}

    # Which folder do you want your Github Page to use as root directory. Usually it is your build output directory such as ./dist 

    build_path: # optional, default is ./dist

    # Desired name for the Deployment environment. It is also the exposed artifact name which contains the build output (dist).

    artifact_name: # optional, default is github-pages

    # Controls the debug mode, boolean, true is for on. When turned on, it'll output certain information on certain steps. Mainly used for development, but use it as you please to inspect your env and variables.

    debug_mode: # optional, default is false

    # Your preference of package manager: 'npm' and 'yarn' are possible values.

    package_manager: # optional, default is npm
